### ISSUE TITLE
Unused Suspect Line

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#10]
There is an unused piece of dialogue for when a suspect kills another suspect by accident. We should probably look into implementing that.

**Comment by sandman332** [comment]
Just wanted to add these in here as well.

I wanted to say there are also some unused lines that the player (lead) has.  "ArrestedSuspect" are lines that the officer ai uses and lead also has them, but for whatever reason they never trigger.  

There is also "ReassuredAggressiveHostage" and "ReassuredPassiveHostage" that lead has lines for, but never trigger, they do however work for the swat officer ai that uses them.  

There are also lines for toc giving lead the go ahead for starting a mission, and lead responding but this also is not implemented.  

There is also "RepliedSuspectRestrainedWithDrugs" which never triggers with the player, or swat officers, even when arresting a Hispanic drug dealer or anyone for that matter.

Along with these others,
AnnouncedSpottedOfficerSurprised
ReactedDownSuspect
ReportedBarricading (not to be confused with announcedbaricade lines)
ShotAFriend
ShotAtBreachedDoor  (This one is fixed now as I see you guys added it in)

**Comment by jose21crisis** [comment]
I once managed to get AnnouncedSpottedOfficerSurprised to work. When a suspect was surprised and complied he would trigger this line. ReactedDownSuspect would be good if we can make it so that suspects barricade after seeing a body. ReportedBarricading is an anwser to AnnouncedBarricade I think, so we need to find a way to trigger both lines on two different suspects. How we trigger ShotAFriend? I couldn't find a way to add it.

**Comment by sandman332** [comment]
I'm not sure about how to go about triggering it.  Maybe a way like how they do for "ReactedDownOfficer"?  But instead of doing it for when they kill an officer it's done for when they kill a suspect?  Just doing it for injuring a suspect I don't think would work.  But then that would mean finding something for "ReactedDownSuspect" to be triggered for as well.

I also forgot to mention that hostages also have this line "ReactedOfficerDown" that never plays.  Maybe it could be implemented the same way that suspects use "ReactedDownOfficer" so that if a hostage is nearby when a suspect shoots an officer the line will trigger for hostages as well?

The other ones I listed should be easy to implement for the lead character ("ArrestedSuspect", "ReassuredAggressiveHostage" and "ReassuredPassiveHostage") since the ai officers have these lines and they already work fine, just not for lead/player.
