### ISSUE TITLE
Stopping power for some weapons doesn't seem right

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#133]
**Suppressed MP5, AP Ammo:** Too weak. Unarmored suspects and civilians can easily survive 10 - 15 shots to the upper body, or 3 - 5 shots to the head, _without even being downed_. When the target does finally go down, they are almost always incapacitated instead of killed, even if all of the shots were headshots. This effectively makes the Suppressed MP5 the best non-lethal weapon in the game, since the player can casually spray half a magazine into a suspect on full auto with zero risk of killing the suspect, or shoot non-compliant hostages until they surrender without any penalties.

**Suppressed MP5, JHP Ammo:** Too powerful. A single shot to the torso will incapacitate or kill any unarmored suspect or hostage.

**MP5SD6, AP Ammo:** Too powerful. Two shots to the torso will incapacitate or kill any unarmored suspect or hostage.

**UMP45, JHP Ammo:** Too powerful. A single shot to _any_ part of the body will almost always _kill_ the target.

**UMP45, FMJ Ammo:** Too powerful. Two or three shots will almost always kill the target.

I haven't tested every combination of weapon and cartridge but so far haven't noticed any other obvious balance issues. I am not sure how to change the stopping power of a weapon/cartridge, so I haven't made any attempt to balance them myself yet.

**Comment by kevinfoley** [comment]
@eezstreet I've been doing more testing with different weapons and have spotted several combinations that seem very unbalanced. I've updated the issue name and description.

**Comment by theengineertcr** [comment]
Yea, weapons are horribly balanced. You can easily just wipe everyones face off the earth with 1 shot or take forever.

**Comment by jose21crisis** [comment]
Weapons are NOT BALANCED AT ALL. I wasn't looking for balance when I edited the weapons, I was looking for realism, since this is a mod that is based on realism, instead of a MP mod, which needs balancing. AP rounds are really hack-ish, because they use negative internal damage, at times lowering the damage to "Too damn low" and other times keeping it "Too damn high", mostly due to SWAT 4's momentum system, which I hate.

As for those combinations
**Suppressed MP5, AP Ammo:** See above
**MP5SD6, AP Ammo:** See above
**UMP45:** I honestly don't see the problem with both of these combinations. .45 ACP IRL is very powerful.

The proper way to fix this would be to make a different ballistic system, that uses "wounds" instead of "health". You can take a maximum amount of wounds before getting downed, each shot can cause a certain amount of wounds depending on energy/momentum/something and armor used.

**Comment by jose21crisis** [comment]
The mass of the ammo types are off.........I'll fix that

**Comment by kevinfoley** [comment]
@jose21crisis I understand you are looking for realism, but the current settings are not realistic. I understand that there are some technical challenges with the AP ammo, but that doesn't change the fact that the current settings are not realistic. 

Additionally, although the .45 ACP is generally regarded as having more stopping power than 9mm, .45 ACP in hollowpoint is absolutely not a guaranteed instant one-hit kill anywhere on the body in real life. If you research modern opinions on pistol cartridge stopping power, many sources agree that shot placement is far more important than the caliber of the cartridge, and many departments are using 9mm instead of .45 ACP because the difference in stopping power isn't very noticeable and it's easier for the officers to control the recoil and keep hitting their target.

**Comment by theengineertcr** [comment]
The torso is randomized randomized as to 1reason and there's 2 solutions:

**Reasoning behind this**
We cannot implement a proper body damage model as the natives block it off somehow(unsure what eez said but it has to do with this). If we could, I can and would've implemented new bones around the body to seperate shots around the heart, lungs, maybe even seperate the jaw from the head.

Current solutions: Remove multipliers, add in random strike chance. Random strike chance seperates the hit chance of an organ. E.g, 40% chance for a shot in the torso to be a shot within the stomach/chest region. 30% chance to hit the lungs, 5% chance to hit the heart and etc. 

Solution 2 which I propose to be added:Find a way to bypass the natives to add in new hit zones either by bones or some sort of code which checks where the bullet has impacted the body. 

Solution 3:Make this an overhaul of SWAT 4, replacing files to bypass any natives that will stop development of new additions.

**Comment by kevinfoley** [comment]
Bullets going through a torso in real life tend to change directions as they tumble through flesh or deflect off bones, so random strike chance isn't a bad solution.

**Comment by jose21crisis** [comment]
Again, SWAT 4's momentum system is something I hate. It favors high mass bullets (.45 ACP) over high velocity bullets (9x19mm and 5.7x28mm), and the multipliers don't help. I made a PR that lowers torso damage to a more reasonable not always 1 shot multipliers. But the whole multiplier thing is still annoying.

The way I wanted it is similar to how Ghost Recon handled it. First, get damage information based on the bullet, its muzzle energy, its velocity and those stats at range. That generates a "Damage" stat. I'll take the M4, the MP5 and the M1911 as examples for this.
After the calculations we get that, at the muzzle, the weapons do this amount of damage:

M4: 2772
MP5: 1034
M1911: 968

Then, this "Damage" stat is used in a formula that looks like this:
1-(BodyPart Wound Factor/Cartridge Damage)
On Ghost Recon, the torso wound factor is 100, so replacing everything on the formula we have:

M4: 1-(100/2772) = 0.96 = 96%
MP5: 1-(100/1034) = 0.90 = 90%
M1911: 1-(100/968) = 0.90 = 90%

In other words, the M4 would have a 96% chance of causing a wound at point blank, the MP5 would have a 90% chance of causing a wound, the same as the M1911 (btw, similar stopping powers)

After this calculation is done, the person shot might or might not get a wound. If he does get a wound, the bodypart wound factor is substracted from the damage and the formula is used with the new damage. In other words, one shot can cause more than 1 wound at a time.

Now, Body Armor can lower the chances of getting a wound. In the case of Level II armor (SWAT 4's light armor) the torso body part wound factor increases to 750, which in the formula means:

M4: 1-(750/2772) = 0.73 = 73%
MP5: 1-(750/1034) = 0.27 = 27%
M1911: 1-(750/968) = 0.22 = 22%

The MP5 barely has chance to do wounds, and the M1911 is even worse (realistic, .45 ACP is bad against armor).

This is however a bit impractical for SWAT 4, since bullets like 5.7x28mm, which have high armor piercing capability but low stopping power, would have too low stopping power against armored targets. This could be adjusted though, adding some kind of "Armor Penetration" stats.

Also, every character in GR had a stat called "Stamina". This stat indicated how many wounds a soldier could take before getting killed. A soldier with 1 stamina point could take only one wound, then second wound would kill him (there is no incap state in GR). A soldier with 8 stamina points could take 8 wounds before going down. Usually, soldiers with LMGs would have 8 stamina points, since they take lots of fire.

Anyway, the point is: SWAT 4's damage system right now is dumb. And I would like to add a new damage system like the one displayed above

**Comment by kevinfoley** [comment]
What file(s) are the damage calculations made in right now?

**Comment by jose21crisis** [comment]
SWATAmmo.u stores the mass and internal damage of each cartridge. SwatEquipment.ini stores the muzzle velocity of each weapon. The damage formula right now is.

((Velocity x Mass)/10) + Internal Damage = Damage

For the MP5, FMJ this is: ((20185 x 0.0146)/10) + 5 = 34

Then that damage is used by the multipliers to get the damage done to the pawn: On V5 those multipliers are 1.5-2.5. On the PR I made I lowered that to 0.8-2.0. So on V5 the damage would be 51-85. and on my PR the damage would be 27-68. 

The thing is, the game also accounts for overpentration, so the damage might be lower if the bullet simply overpenetrates and is not lodged in the bodypart of the person shot.

**Comment by jose21crisis** [comment]
Ignore that last part........I don't know where the formulas are

**Comment by eezstreet** [comment]
I'm in favor of changing the damage model to use something else, if only because using actual real values produces totally wrong results, and we've been having to fudge some values for specific things in order to make them sorta realistic...which *is not realistic at all.* 

What I'd like to implement, and what is probably impossible, is a model that allows for different hit regions based on an internal skeleton representation of what gets hit, and a blood count. So something similar to Sniper: Elite, in other words. But since this is a pretty old engine, it's unlikely we're going to ever get anything that good.

A hit system like what @jose21crisis describes sounds better, but I'd add a few more variables to the mix to make it a little more rooted in ballistics:
 * Drag, which already exists in SEF (although it might be a bit too high by some estimates)
 * Tumble chance, which dictates the frequency of a bullet tends to tumble in travel
 * Tumble damage min/max, which dictates the additional damage caused by tumble
 * Expansion, which dictates how wide a bullet expands when it embeds itself in a surface
(these last three parameters are kinda sorta supposed to be modeled by InternalDamage, but it's not really used like that at the moment)

I think a "stamina" system might make it a bit too game-y, but I'd add in a bleedout system, so if a suspect gets wounded and runs off, they might later die from their injuries. (but do add a visual indicator! like bloodstains on clothes or something, just so the player doesn't go WTF?)

**Comment by theengineertcr** [comment]
We should be having impact wounds as well and blood dripping, not sure how but it would be perfect. However, how will the bleedout rate get decided? I'd also like to know how the hitregion thing is coded and where it's coded, I want to try and increase hit regions, even if there is a limitation.

**Comment by kevinfoley** [comment]
> I'd add in a bleedout system, so if a suspect gets wounded and runs off, they might later die from their injuries. (but do add a visual indicator! like bloodstains on clothes or something, just so the player doesn't go WTF?)

On that note, I'd like to see fewer instant fatalities (after all, only a direct hit to the heart or central nervous system should be an instant fatality), and add a 'life-threatening injury' system. Actually, I think I'll create a separate issue for that.
