### ISSUE TITLE
Suspects who shoot or damage someone should be a threat at ALL times

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#152]
You can easily lose missions because of 1 unauthorized deadly force or lethal force. This is completely stupid that a person, who shot me 5+ times, that I kill as SOON as I get 1 lucky shot that makes him drop his gun and shoot him again. Why does this happen sometimes? I don't want to restart an entire mission because of 1 guy dying to lethal force. This also happens if they don't comply AND aim their gun. Whether they are playing their stunned animation or not, they should be threats. Let's get more improvements on this thing please.

**Comment by kevinfoley** [comment]
My opinion is that there should be a grace period between when suspects become non-threatening and when you are penalized for killing them. It's currently too easy to be unloading at a suspect and accidentally kill him right as he drops his weapon or turns to flee. The 20-point penalty for fatally wounding the suspect in this instance is essentially an instant fail on Hard and above. 

In real life, police are _trained_ to keep shooting until the suspect goes down and _stops moving_. If you watch body-cam footage of real-life police shootings, you'll see that 90% of the time, once anyone has fired a shot, every officer present will unload his current magazine into the suspect. This is to make sure the suspect is truly incapacitated and doesn't have an opportunity to fire back.

I'm not trying to make this political or get into a debate about justifiable use of force, but right now I think the game is too strict, forcing you to play it like a game rather than a simulation. We already lose points for killing (rather than arresting) suspects even when we _aren't_ penalized for accidental unauthorized use of force. I find myself spending too much time worrying about my score rather than what a real officer would be worried about - the safety of his team and the public, and doing stupid unrealistic things like shoot the suspect once in the arm or leg, wait to see if he surrenders, and then shoot him again if he raises his weapon.

**Comment by theengineertcr** [comment]
There should be a grace period(I've asked for this before but never saw it get added), I'd say a minimum of 1-2 seconds would be good enough.

**Comment by eezstreet** [comment]
I'll defer to @jose21crisis about adding a grace period since he's dealt a lot with the threat stuff.

**Comment by jose21crisis** [comment]
I would say just make suspects that at any point were a threat can be neutralized, even if they surrendered (which is how SWAT 3 handled it btw). For the grace period, I would need to make it so that the Unauthorized Force penalties look directly at the pawn's bThreat property for determining when was threatening or not. It uses a different procedure right now. Then make it so that the compliance action triggers the UnbecomeAThreat() function after 1.5-2.0 of it being started.

**Comment by kevinfoley** [comment]
I don't like the idea of being allowed to kill a suspect who has clearly surrendered just because he fired his weapon earlier. Are you saying it will be overly complicated to implement a grace period?

**Comment by jose21crisis** [comment]
No......just saying that it would be easier to make it so that threatening suspects are always threatening even after they surrender, but I prefer the grace period.

**Comment by eezstreet** [comment]
I've separated the grace period discussion into a separate issue. The grace period should be very very short though, like < 2 seconds.
