### ISSUE TITLE
AI first removes wedge before breaching a Door.

### ISSUE THREAD

**Issue by dedmen** [eezstreet/SWATEliteForce#261]
Wedge a door. Tell AI to shotgun breach&enter. AI will first remove wedge before they attempt to breach.

**Comment by dedmen** [comment]
That's intended.
The wedge would block the door from opening even if you breach it.

**Comment by theengineertcr** [comment]
Does telling them to deploy a shotgun remove the wedge? That would be a bug.

**Comment by eezstreet** [comment]
Why would they deploy a shotgun on a door that they didn't intend to open?
________________________________

**Comment by theengineertcr** [comment]
If you command them to deploy a shotgun on a wedged door, not breach with shotgun enter and clear which then they will remove the wedge. Same can be with C2, will AI remove a wedge if they've been only ordered to deploy the C2 rather than breach with c2 enter and clear? I'll be checking later anyway if I got time.

**Comment by dedmen** [comment]
As I wrote the command I issue was "shotgun breach & enter" 
Didn't try with deploy shotgun.

But I actually do a purpose in using a shotgun and not actually opening the Door. You can easilly look through the hole.
