### ISSUE TITLE
Officer stuck in reloading shotgun loop

### ISSUE THREAD

**Issue by themaster567** [eezstreet/SWATEliteForce#286]
For some context, I equipped everyone with less-lethal beanbag shotguns. Specifically, the more compact shotguns(don't remember their name). Giving an order solves the issue.

**Comment by sandman332** [comment]
The new beta introduced the ability for officers to reload all of their shotgun rounds.  So you are correct you are seeing a loop.  However, once their shotgun is full (8 rounds for most?) Do they still do it?  

This change was made so that they reload ALL of their rounds in the shotgun before shooting again.  Instead of the stupid reload 1 shell, shoot, reload again.

**Comment by themaster567** [comment]
It happens forever. The beanbag shotgun I'm using only holds 5 rounds, so it's pretty easy to notice when it goes over that.

**Comment by eezstreet** [comment]
I've pushed a fix upstream which may fix this.

**Comment by eezstreet** [comment]
Seems to be fixed.
