### ISSUE TITLE
Request: increase bleedout timer for DuPlessi civilians

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#329]
It can be very difficult to clear DuPlessi's Diamonds with a perfect score because of how quickly the civilians bleed out. Faceman has suggested that we increase the bleedout timer for these so the mission is easier in singleplayer.

Thoughts?

**Comment by sandman332** [comment]
I agree, maybe an extra 5 or 10 minutes?

**Comment by theengineertcr** [comment]
I think that the bleedout timer should be difficulty dependant as SWAT Teams using full dynamic tactics with proper strategies would possibly be able to clear it and rescue all civis ASAP. I haven't played in some time so I'll have to recheck to see how possible it is to do this.

**Comment by jose21crisis** [comment]
Try to go faster. I was able to clear it going dynamic with each and every civilian unharmed.

**Comment by jose21crisis** [comment]
Unless you scale it with difficulty that is. I was able to pull of that on Hard, so it is very possible if someone moves fast enough.

**Comment by theengineertcr** [comment]
We need to have exact times of each downed civi players report so that we can have an accurate measurement of how fast and slow people can finish the map, how many civi's turn into a doa, what was their initial time and what time did the player reach and report a doa on them. After that, we'll compare and contrast the best and worst times before debating what doa time civis should have on this particular mission. We could go ahead and call on the testers to do a run on Duplessis 100% and have them report back their times as well as providing the files.

**Comment by Gliptal** [comment]
What do you guys mean with "going dynamic"?

**Comment by theengineertcr** [comment]
Moving fast, being loud, clearing rooms quickly and effeciently. No brakes
or stops, just keep going, secure anyone who surrenders and report to
toc/secure guns as sook as you can.
