### ISSUE TITLE
Respirator Camera Visuals

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#357]
I suggest to add respirator visuals to a camera while wearing a respirator. Those should restrict view a little and make player being aware he is wearing it, to not forget to equip it.

**Comment by eezstreet** [comment]
Disagree. Part of the reason I removed the respirator visuals in the first place is that there was no good option of unrestricted view when going on a gas mission. Now there is, and the choice is between whether you want good field of view and lighter weight with no protection vs restricted field of view and heavier weight with added protection.

Now that being said, using gas on missions is way too strong, primarily because gas in the game is not modeled to real life (in reality, gas can be rendered useless if there's strong wind, if the suspects in question aren't very exposed to it, aren't exposed long enough, etc, and it is not fully effective in dealing with a determined enough suspect)
