### ISSUE TITLE
Gigabytes of log files

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#44]
From admin@induktio.net:

1. It will continuously fill logs with repeated lines, which quickly
increase log size to gigabytes. See the attachment. It will also print
every second:
ScriptLog: (t=39075.646): [LEADERSHIP] Procedure_NoTrapsTriggered is
returning with NumTrapsTriggered = 0

**Comment by jose21crisis** [comment]
Release build should not have this problem, considering that we should suppress that stuff in the Swat4x.ini file

**Comment by induktio** [comment]
Can you elaborate on how that output is suppressed? I think in this case it used Swat4XDedicatedServer.ini because it was running as a dedicated server. It might have been missing some variable from the ini file.

**Comment by jose21crisis** [comment]
You need to edit SWAT4X.ini, not necesarily Swat4XDedicatedServer.ini. Find this section: 
[Core.System]
PurgeCacheDays=0
SavePath=../Save
CachePath=../Cache
CacheExt=.uxx
DisableAccessedNoneWarnings=0
;Suppress=DevLoad
;Suppress=DevSave
;Suppress=DevNetTraffic
;Suppress=DevNetTrafficRPC
;Suppress=DevGarbage
;Suppress=DevKill
;Suppress=DevReplace
;Suppress=DevCompile
;Suppress=DevBind
;Suppress=DevBsp
;Suppress=DevAssert
;Suppress=ScriptLog
;Suppress=GUIScriptLog
;Suppress=WindowedMode
Suppress=ScriptWarning
Paths=*.u
Paths=../Maps/*.s4m
Paths=../Art/*.pkg
Paths=../Textures/*.utx
Paths=../StaticMeshes/*.usx
Paths=../Animations/*.ukx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Paths=../Saves/*.uvx
Paths=../Classes/*.u
Paths=../CustomSkins/*.skn
Paths=../Test/Maps/*.s4m
Paths=../Test/Maps/MilestoneDemos/*.s4m
Paths=../Test/Art/*.pkg
Paths=../Test/Textures/*.utx
Paths=../Test/StaticMeshes/*.usx
Paths=../Test/Animations/*.ukx
Paths=../Test/Sounds/*.uax
Paths=../Test/Sounds/*.umx
Paths=../Test/Music/*.umx
Paths=../Test/Saves/*.uvx
Paths=../Test/Classes/*.u

And look for this lines:
;Suppress=WindowedMode

Erase the ; so that it looks like this:
Suppress=WindowedMode

And do the same for the other ones in that section.

**Comment by induktio** [comment]
Well, I don't see WindowedMode having any effect on those logs. Anyway, I noticed my Swat4XDedicatedServer.ini had these lines:
`;Suppress=ScriptLog
;Suppress=ScriptWarning`
After uncommenting the lines above the warnings disappeared and the logs got a lot smaller.
