### ISSUE TITLE
No sound on Lenovo Legion Y540

### ISSUE THREAD

**Issue by sukhoi191** [eezstreet/SWATEliteForce#516]
When I play vanilla game from [GOG](https://www.gog.com/game/swat_4_gold_edition), audio works without any problems. But, when I launch the game through the mod launcher (LaunchSEF.bat), all sound is gone and by "all", I mean everything, including programs playing audio in the background. It looks like the game tries to get an exclusive control over the sound.

I didn't touch the configuration. Also, I've found nothing too suspicious in the log file (see the attachment: [Swat4X.log](https://github.com/eezstreet/SWATEliteForce/files/4990864/Swat4X.log)).

What can be the cause of this issue? If you need any more info, please let me know. I'm trying to troubleshoot it by myself, but comparing original configuration files with mod-related ones don't seem to contain changes, which may cause such problems.

**Comment by sukhoi191** [comment]
Ok, it's not the mod that causes this issue. I was launching vanilla SWAT 4, i.e. without The Stetchkov Syndicate addon. Launching the game with The Stetchkov Syndicate and without EF mod also causes problems with the sound.

**Comment by sukhoi191** [comment]
Solved it. If anyone comes across a similar problem (it may be me in the future), it turns out that the cause was my headphones (Sound Blaster JAM). They are detected in Windows as two different devices - first one is used for audio output such as music, games etc., and second one for voice communication (output + input). Disabling the device used for communication solved the problem.

**Comment by eezstreet** [comment]
Thanks. I will make a note of this in the README file.

Sent from my iPhone

On Jul 28, 2020, at 4:48 PM, Bartłomiej Zieliński <notifications@github.com> wrote:

﻿

Solved it. If anyone comes across a similar problem (it may be me in the future), it turns out that the cause was my headphones (Sound Blaster JAM). They are detected in Windows as two different devices - first one is used for audio output such as music, games etc., and second one for voice communication (output + input). Disabling the device used for communication solved the problem.
