### ISSUE TITLE
Readme file outdated

### ISSUE THREAD

**Issue by rubycookinson** [eezstreet/SWATEliteForce#552]
The readme file reads:

> To run the game, use the "Launch SEFMod.bat" file. To run SWATEd, use the "Launch SwatEd.bat" file. You can make a shortcut to these .bat files for more convenience.

There is no "SEFMod.bat" file in the github. It is just "LaunchSEF.bat" Also maybe mention there is an .exe?

Just a minor correction that needs to be made. Been bugging me for a while.

**Comment by T-MaxWiese-T** [comment]
Yeah, that's right. Especially the LaunchSEF.exe is important to me. It was added mainly because of Gameranger but it doesn't change the fact that everyone else should use it as well. I suggest to put the LaunchSEF.exe into the SEF folder. You have to check that the .exe is forced in administrator mode, so that there are no more problems with write permissions.

**Comment by T-MaxWiese-T** [comment]
#554
