### ISSUE TITLE
Multiple weapons use the MP5 sound

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#76]
Not sure about SWATs using m249 though.

**Comment by eezstreet** [comment]
I'm going to hazard a guess and say that this affects more than just the M249, because a lot of full auto weapons don't have their own ThirdPersonBurstFired sound effect specification, which is what's used when firing in full auto mode.

Checking in the SoundEffects.ini, it affects all of the TSS weapons (P90, M249, TEC-9)

**Comment by eezstreet** [comment]
The file for this is on the stack; the issue will be fixed when Moretti dialogue is implemented.

**Comment by theengineertcr** [comment]
Request this to be opened again, there are still some weapons with MP5 sounds again.

**Comment by theengineertcr** [comment]
Suspect "Pistol Grip Pump Shotgun" uses an MP5 firing sound.
