### ISSUE TITLE
Darker's list of suggestions and issues with SEF

### ISSUE THREAD

**Issue by Darker1990** [eezstreet/SWATEliteForce#94]
SEF Bug and suggestion list

Beta 6
1st April 2017

1.	On certain maps (e.g. Foodwall, Tenement and A-Bomb) people seem to be falling through floors when engaged.

2.	Swat officers do not change their position to have a clear line of fire when you start team killing in comparison to swat 3.

3.	Upon first start after patching to beta 6 it is possible to have AI officers equipped with night vision even though the team leaders is not officially supposed to select this due to unlocking.

4.	AI officers seem to be having a strange idle animation where they stand with one weapon carrying the gun and the other being idle

5.	Seems that you also still able to fire your gun while being cs gassed. Shouldn’t it be so that professional swat officers do not engage when they are not 100% able to distinguishing between a threat and non threat?

6.	On Foodwall map officers seem to be shooting left from the metal door with the staircase when trying to breach open the door. They end up in a loop shooting their gun dry then reloading one slug and try indefinitely.

7.	AI officers are unaffected by CS gas even though they have only helmets like the element leader who is affected. Moreover AI officers enter directly when gas canister has landed in the room without waiting before it starts to emit gas. There is no option to equip fellow officers with gas masks due to the unlockables.

8.	When you giving AI officers a quick loadout from the dropdown menu, changing subsequently individual items like guns does not seem to be put into effect ingame.

9.	Currently there is no ability to repin a grenade in order to store it again. You are forced to use it.

10.	It is currently possible to use the optiwand to see through AI officers and sometimes walls of the map. However when close to objects the screen turns blue.

11.	It would be nice if you would get unnecessary use of force when punching, tazing, pepper spraying a civilian or suspect that is already handcuffed. It is something that happens to much in online Co-op by noobs.

12.	Sometimes you seem not to be able to punch civvies when equipped with handcuffs. Its an original bug.

13.	Upon changing from handcuffs to your main gun the weapon animation seems glitched where your gun floats in mid air before returning to your hand. This is an original game bug.

14.	You currently do not have the ability to properly “relocate” civilians/suspects from dangerous places. They sit on their knees and can sometimes become hit during intense fire fights. Although crouching near them results in the moving of the person, this is often cumbersome. 

15.	You are able to C2 broken doors currently which results in the strange placement and floating of C2 charges in mid air.

16.	Suspects can be easily unarmed when shooting their shoulder. However when playing custom QMM, suspects can be equipped with 2 assault rifles so that they have a new assault rifle easily ready when the first one is dropped. But shouldn’t they be able to not use those weapons at all when heavily injured in the shoulder?

17.	 Suspects only fire 4-5 rounds at a door when it is opened by SWAT. Then it stops. For more realism and stress it would be nice to have more shots occurring. This since suspects have “unlimited” ammo.

18.	You are not able to currently punch your officers. It would be nice if you would hear a sound such as "hey watch it" like those that are played when you use the bean bag on a fellow officer

19.	Currently repacking of magazines is not possible. A lot of people reload when they only have a few bullets left in the magazine. Eventually you end up with one or 2 bullets in 5-6 magazines. Not really good for when you want to engage suspects. On the other hand, repacking your magazines in the field is also not really.....uhm professional and "safe". Moreover you cannot exchange magazines with a fellow officer.

20.	Currently it is still possible to equip two pistols and multiple pepper sprays.

21.	Certain textures of guns (such as MP5) were tweaked by SAS mod. You might be able to use those with permission.

22.	Please include this guy’s work: http://www.moddb.com/mods/equipmentmod-by-bbe/images/helmet-and-gasmask#imagebox I already contacted him and asked and I am awaiting a response.

23.  Ten years ago Gez (of the Gez modification) seems to have created a GUI controled system that allowed custom skins to have custom models. In other words, one would no longer be restricted to the standard SWAT officer model when making new skins. Imagine selectable streetcops, sheriffs, undercover agents. Complemented with a great variety of headgear and equipment. Gez committed to this project by donating his time and knowledge to implemented this custom character selection. It would be a nice addition to SEF.

24. The in-hand placement of the P90 seems horribly wrong.

**Comment by theengineertcr** [comment]
Multiple peppersprays is a base game thing and after you run out of a pepperspray can you can use another. As for the others, I recommend making each issue seperate rather than altogether.

**Comment by jose21crisis** [comment]
Ok, let's see

1. I've seen incaps falling through the floor, although only 2 times, one on A-Bomb, one on Taronne's
2. Maybe we can make it so that they use the same code they use when engagine suspects.
3. I'm pretty sure it only happens when you select the NVGs on a campaign that has them unlocked, then go to a campaign that doesn't have them unlocked. Maybe force the player to change equipment if the equipment piece is not unlocked?
4. Most likely fixed on V5 release
5. This only happens on SP, since you weren't supposed to be gassed on SP. That's right, and officers should use their own judgement for that. If you are gassed, but can see what appears to be a threat, it is your call whenever to shoot, issue compliance or take cover.
6. Ahhh.....this bug. If we release a patch for v5, this will be fixed.
7. On the first part, maybe it can be implemented. On the second part, there is an apparent fix that may appear on v5 patch.
8. Hmm.....must be a fluke or something. Everytime I switch equipment after selecting a custom loadout, then I change individual weapons/tactical aids, the effects appear in-game
9. You don't repin grenades in the field.
10. Have not experienced this one
11. This is a good idea. I want it.
12. Noted.
13. Yep, base bug. We're not sure where it comes from though.
14. Not sure if we can make a proper "relocate" option. We might be able to.
15. Noted.
16. When you shoot the shoulder/arm/hand, they drop the weapon. That doesn't mean they can't use other weapons, it just means that they will be very innacurate. IRL you can have a broken arm and still be able to use a weapon, but you won't be as accurate as you used to be.
17. Suspects have limited ammo. They only fire 4-5 rounds when they have pistols. With automatics they fire longer bursts of up to 10-15 rounds.
18. Noted. I like this one.
19. Magazine repacking is done in an armory, not in the field.
20. Multiple pistols..........this is (or at least was) done by some SWAT times. They carry 2 pistols, in case one jams. They are used this way because they are good in condensed areas, as pistols are easier to handle than SMGs or Rifles.  Multiple Pepper Sprays............Why exactly you can't carry more than 1 OC cannister?
21. We want to add some HD textures for a lot of stuff, not just weapons.
22. That is eez's jurisdiction, so to speak.
23. See 22
24. If you mean third person hand placement, it was fixed in V5 release. If you mean first person hand placement, then I don't know what you mean, You can't see the hands unless you reload the P90.

**Comment by eezstreet** [comment]
Hi, please make separate issues instead of making huge lists.
