### ISSUE TITLE
Suspects can be exploited by running around them

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#97]
Running to the left/right or around the suspect will stop them from firing until you stop.

**Comment by eezstreet** [comment]
Just to note, this has always been an issue in the original game, just more noticeable in SEF since suspects have a delay before they can fire.

**Comment by jose21crisis** [comment]
Note: This problem not only appears in SWAT 4. Rainbow Six Raven Shield, a game which uses the same engine (Unreal Engine 2) suffers the same problem, the only difference is that the enemies actually fire, instead of just aiming.

Anyway, I might be able to make them fire, even when their aim is imperfect.

**Comment by eezstreet** [comment]
Is this still an issue? I believe we've corrected it now.

**Comment by theengineertcr** [comment]
This is still an issue. You can run into suspects and push them around or run around them, they'll be confused and won't be able to shoot.
